import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');
const BOTTOM_INSET_MIN = Platform.OS === 'android' ? 48 : 34;
const FUNNYFY_FOLDER_NAME = 'Funnyfy';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  splashSafe: {
    backgroundColor: '#ffffff',
  },
  splashContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashImage: {
    width: 220,
    height: 220,
    borderRadius: 28,
  },
  container: {
    padding: 20,
    paddingTop: 16,
    paddingBottom: 20,
    gap: 16,
    flexGrow: 1,
    alignItems: 'center',
  },
  resultContainer: {
    flex: 1,
    padding: 20,
    paddingTop: 16,
    gap: 0,
  },
  styleContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 0,
    flexGrow: 1,
  },
  fixedHeader: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    zIndex: 10,
  },
  uploadContainer: {
    flex: 1,
    padding: 24,
    paddingTop: 8,
    gap: 16,
  },
  uploadHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 8,
    marginBottom: 4,
  },
  resultHeader: {
    paddingTop: 8,
    paddingBottom: 12,
    marginBottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  uploadImageContainer: {
    flex: 1,
    justifyContent: 'center',
    minHeight: 200,
  },
  uploadButtonsContainer: {
    gap: 12,
    paddingBottom: Platform.OS === 'android' ? 8 : 8,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: '#111827',
    marginTop: 4,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    color: '#6b7280',
    fontWeight: '500',
    lineHeight: 22,
  },
  subscriptionSummaryContainer: {
    marginTop: 8,
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  subscriptionPlanPill: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#eef2ff',
  },
  subscriptionPlanPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4f46e5',
  },
  subscriptionRefreshButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  subscriptionRefreshText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4b5563',
  },
  subscribeButton: {
    alignSelf: 'center',
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: '#111827',
    borderRadius: 12,
  },
  subscribeButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 4,
    marginBottom: 0,
    textAlign: 'center',
  },
  sectionLabelSelected: {
    color: '#f97316',
    fontWeight: '800',
  },
  styleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  card: {
    backgroundColor: 'transparent',
    borderRadius: 16,
    padding: 0,
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
    width: '48%',
    marginBottom: 16,
  },
  styleCard: {
    marginTop: 0,
    marginBottom: 16,
  },
  styleCardSelected: {
    transform: [{ scale: 0.97 }],
  },
  cardRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cardHalf: {
    flex: 1,
  },
  styleImageWrapper: {
    width: '100%',
    aspectRatio: 3 / 4.4,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#F7F7F8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  styleImage: {
    width: '100%',
    height: '100%',
  },
  styleImageOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'transparent',
  },
  styleImageOverlaySelected: {
    backgroundColor: 'rgba(249, 115, 22, 0.4)',
  },
  styleImageLabel: {
    color: '#f9fafb',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  previewContainer: {
    flex: 1,
    width: '100%',
    gap: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 200,
  },
  previewCanvas: {
    width: '100%',
    flex: 1,
    maxHeight: 'none',
    minHeight: 300,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#f9fafb',
    borderWidth: 2,
    borderColor: '#e5e7eb',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  previewImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  afterMask: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
  },
  previewOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  sliderHandleContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  sliderLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  sliderKnob: {
    position: 'absolute',
    top: '50%',
    marginTop: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  sliderKnobText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  photoPreview: {
    width: '100%',
    height: '100%',
    maxHeight: '100%',
    borderRadius: 12,
    resizeMode: 'contain',
  },
  photoPlaceholder: {
    width: '100%',
    height: '100%',
    minHeight: 200,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7F7F8',
  },
  photoPlaceholderText: {
    fontSize: 14,
    color: '#9ca3af',
    fontWeight: '500',
  },
  input: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#ffffff',
    textAlignVertical: 'top',
    fontSize: 13,
    color: '#111827',
  },
  button: {
    backgroundColor: '#f97316',
    paddingVertical: 16,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    shadowColor: '#f97316',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  secondaryButton: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  buttonDisabled: {
    opacity: 0.5,
    shadowOpacity: 0.1,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.5,
  },
  secondaryButtonText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  errorBox: {
    backgroundColor: '#fef2f2',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1.5,
    borderColor: '#fecaca',
    marginTop: 8,
  },
  errorText: {
    color: '#dc2626',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  bottomActionsContainer: {
    width: '100%',
    gap: 12,
    alignItems: 'center',
    paddingBottom: Platform.OS === 'android' ? 8 : 0,
  },
  progressContainer: {
    width: '100%',
    marginTop: 0,
    marginBottom: 0,
    gap: 8,
  },
  skeletonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
  },
  skeletonSquare: {
    width: 18,
    height: 18,
    borderRadius: 4,
    backgroundColor: '#0F172A',
  },
  skeletonBar: {},
  progressBarTrack: {
    width: '100%',
    height: 28,
    borderRadius: 999,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
    justifyContent: 'center',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#f97316',
  },
  progressBarLabelWrapper: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressBarLabelText: {
    fontSize: 12,
    fontWeight: '600',
  },
  progressBarLabelTextLight: {
    color: '#f9fafb',
  },
  progressBarLabelTextDark: {
    color: '#374151',
  },
  progressLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4b5563',
    marginBottom: 4,
  },
  errorRetryContainer: {
    width: '100%',
    marginBottom: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FFFBEB',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FDE68A',
    gap: 12,
  },
  errorRetryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  errorRetryTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#92400E',
  },
  errorRetrySubtext: {
    fontSize: 13,
    color: '#78350F',
    lineHeight: 18,
  },
  errorRetryMessage: {
    flex: 1,
    fontSize: 14,
    color: '#92400E',
    fontWeight: '500',
    lineHeight: 20,
  },
  errorRetryHint: {
    fontSize: 12,
    color: '#B45309',
  },
  retryButton: {
    alignSelf: 'center',
    paddingVertical: 11,
    paddingHorizontal: 32,
    backgroundColor: '#0F172A',
    borderRadius: 12,
  },
  retryButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 15,
    letterSpacing: 0.2,
  },
  actionsRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
    marginTop: 0,
    paddingBottom: 0,
  },
  actionButtonWrapper: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
  },
  actionButton: {
    width: '100%',
    minHeight: 52,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  actionButtonText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0.3,
    flexShrink: 0,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  backButtonIcon: {
    fontSize: 32,
    color: '#111827',
    fontWeight: '900',
    textAlign: 'center',
    lineHeight: 32,
    width: 32,
    height: 32,
  },
  homeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  homeButtonIcon: {
    fontSize: 20,
    color: '#111827',
    fontWeight: '900',
    textAlign: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: '#e5e7eb',
    marginVertical: 12,
  },
  badgeAsBarContainer: {
    flex: 1,
    width: '100%',
    height: 32,
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#e5e7eb',
  },
  badgeAsBarFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 999,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  badgeAsBarTextWrapper: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeAsBarText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1f2937',
    textShadowColor: 'rgba(255,255,255,0.9)',
    textShadowOffset: { width: 0, height: 0.5 },
    textShadowRadius: 2,
  },
  uploadSubscriptionBadge: {
    flex: 1,
    width: '100%',
    height: 32,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadSubscriptionBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0F172A',
  },
  resultBadgeAsBarContainer: {
    flex: 1,
    marginHorizontal: 8,
    height: 32,
    borderRadius: 999,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#e5e7eb',
  },
  resultSubscriptionBadge: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
    marginHorizontal: 8,
  },
  resultSubscriptionBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0F172A',
  },
  quotaProgressContainer: {
    marginTop: 8,
    marginBottom: 12,
    gap: 8,
  },
  quotaProgressBar: {
    width: '100%',
    height: 6,
    borderRadius: 999,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
  },
  quotaProgressFill: {
    height: '100%',
    borderRadius: 999,
    transition: 'width 0.3s ease',
  },
  quotaWarningButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#f59e0b',
    alignItems: 'center',
  },
  quotaWarningText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400e',
  },
  quotaExceededButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: '#ef4444',
    alignItems: 'center',
  },
  quotaExceededText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#991b1b',
  },
  headerBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    gap: 10,
  },
  wordmark: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  headerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F7F8',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 8,
    flexShrink: 1,
  },
  headerPillProgress: {
    width: 36,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    overflow: 'hidden',
  },
  headerPillProgressFill: {
    height: '100%',
    backgroundColor: '#0F172A',
    borderRadius: 2,
  },
  headerPillText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#0F172A',
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F7F7F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonIcon: {
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '600',
  },
  styleCardLabel: {
    marginTop: 8,
    paddingHorizontal: 2,
    alignItems: 'center',
  },
  styleCardName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0F172A',
    lineHeight: 19,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  styleCardDesc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
    textAlign: 'center',
  },
  photoPlaceholderIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  photoPlaceholderIconText: {
    fontSize: 28,
    color: '#0F172A',
    fontWeight: '300',
    lineHeight: 32,
  },
  photoPlaceholderTitle: {
    fontSize: 15,
    color: '#0F172A',
    fontWeight: '600',
  },
  photoPlaceholderHint: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  cropChip: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 99,
  },
  cropChipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  uploadSourceRow: {
    flexDirection: 'row',
    gap: 10,
  },
  slimButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  slimButtonText: {
    color: '#0F172A',
    fontWeight: '600',
    fontSize: 14,
  },
  primaryButton: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  quotaExceededBanner: {
    backgroundColor: '#FEF2F2',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  quotaExceededBannerText: {
    color: '#A32D2D',
    fontWeight: '600',
    fontSize: 13,
  },
  photoChooserContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  photoChooserHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  photoChooserLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoChooserEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoChooserEmptyText: {
    fontSize: 16,
    color: '#64748B',
    fontWeight: '500',
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingVertical: 8,
    gap: 8,
  },
  photoGridItem: {
    width: '48.5%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F7F7F8',
  },
  photoGridImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  menuSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 8,
    paddingHorizontal: 8,
  },
  menuHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E5E7EB',
    marginBottom: 8,
  },
  menuHeader: {},
  menuHeaderIcon: {},
  menuHeaderIconText: {},
  menuHeaderTitle: {},
  menuHeaderSub: {},
  menuDivider: {},
  menuItemsContainer: {},
  menuItemDivider: {},
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  menuItemIcon: {
    marginRight: 14,
  },
  menuItemIconWrap: {},
  menuItemContent: {},
  menuItemText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '400',
    color: '#0F172A',
    letterSpacing: 0.3,
  },
  menuItemDesc: {},
  menuItemArrow: {},
  galleryContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  galleryClearIcon: {
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '600',
  },
  galleryHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  galleryLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    gap: 12,
  },
  galleryEmptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  galleryEmptyIconText: {
    fontSize: 26,
    color: '#0F172A',
    fontWeight: '600',
    lineHeight: 30,
  },
  galleryEmptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0F172A',
  },
  galleryEmptyText: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 18,
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingTop: 12,
    rowGap: 12,
  },
  galleryItem: {
    width: '48%',
    marginBottom: 4,
  },
  galleryItemImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: '#F7F7F8',
  },
  galleryItemLabel: {
    marginTop: 6,
  },
  galleryItemStyle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0F172A',
  },
  galleryHint: {
    fontSize: 11,
    color: '#94A3B8',
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
  viewerFooter: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: 'rgba(0,0,0,0.7)',
    gap: 10,
  },
  viewerFooterLabel: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  viewerActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  viewerActionButton: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  viewerActionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  infoContainer: {
    flex: 1,
    padding: 24,
    paddingTop: 8,
  },
  infoContent: {
    paddingTop: 16,
    paddingBottom: 24,
  },
  infoText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#334155',
  },
  paywallContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  paywallPlanCard: {
    backgroundColor: '#F7F7F8',
    borderRadius: 14,
    padding: 14,
    marginTop: 4,
    marginBottom: 16,
  },
  paywallPlanHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  paywallPlanTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0F172A',
  },
  paywallPlanQuotaText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  paywallPlanRenewalText: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 8,
  },
  paywallPendingText: {
    fontSize: 12,
    color: '#0F172A',
    fontWeight: '500',
    marginTop: 4,
  },
  paywallActivePill: {
    backgroundColor: '#EAF3DE',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 99,
  },
  paywallActivePillText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#3B6D11',
    letterSpacing: 0.4,
  },
  paywallUpgradePill: {
    backgroundColor: '#F1F5F9',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 99,
  },
  paywallUpgradePillText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#0F172A',
    letterSpacing: 0.4,
  },
  paywallCancelPill: {
    backgroundColor: '#FAEEDA',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 99,
  },
  paywallCancelPillText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#854F0B',
  },
  paywallProgress: {
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    overflow: 'hidden',
  },
  paywallProgressFill: {
    height: '100%',
    backgroundColor: '#0F172A',
    borderRadius: 2,
  },
  paywallSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0F172A',
    marginBottom: 10,
    marginTop: 4,
  },
  paywallTierCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  paywallTierCardSelected: {
    borderWidth: 1.5,
    borderColor: '#0F172A',
  },
  paywallTierCardCurrent: {
    backgroundColor: '#F1F5F9',
    borderColor: '#0F172A',
  },
  paywallTierRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paywallTierLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    flexWrap: 'wrap',
  },
  paywallTierName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0F172A',
  },
  paywallTierPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  paywallTierPriceUnit: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748B',
  },
  paywallTierDesc: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
  },
  paywallTierBadgeCurrent: {
    backgroundColor: '#0F172A',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 99,
  },
  paywallTierBadgeCurrentText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  paywallTierBadgePopular: {
    backgroundColor: '#0F172A',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 99,
  },
  paywallTierBadgePopularText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  paywallTierBadgeNeutral: {
    backgroundColor: '#F1EFE8',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 99,
  },
  paywallTierBadgeNeutralText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#5F5E5A',
    letterSpacing: 0.5,
  },
  paywallActions: {
    paddingTop: 12,
    gap: 8,
  },
  paywallHeroIconWrapper: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 16,
  },
  paywallHeroIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paywallHeroIconText: {
    fontSize: 26,
    color: '#0F172A',
    fontWeight: '600',
    lineHeight: 30,
  },
  paywallCancelLink: {
    fontSize: 13,
    color: '#A32D2D',
    fontWeight: '500',
    paddingVertical: 8,
  },
  cropScreenSafe: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  cropScreenContainer: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  cropScreenTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#1a1a1a',
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  cropScreenBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  cropScreenBackIcon: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: '600',
  },
  cropScreenDoneButton: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#0F172A',
    borderRadius: 8,
  },
  cropScreenDoneText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  cropScreenCanvasWrapper: {
    flex: 1,
    backgroundColor: '#000000',
    overflow: 'hidden',
  },
  cropScreenCanvas: {
    flex: 1,
    width: '100%',
    position: 'relative',
    backgroundColor: '#000000',
  },
  cropImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  cropOverlay: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  cropBoxBorder: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#0F172A',
  },
  cropHandle: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cropHandleInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#0F172A',
  },
  styleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  menuButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  menuButtonIcon: {
    fontSize: 20,
    color: '#111827',
    fontWeight: '900',
  },
  subscriptionContainer: {
    padding: 24,
    paddingTop: 60,
    gap: 24,
    flexGrow: 1,
  },
  subscriptionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  subscriptionHeaderContent: {
    gap: 2,
  },
  subscriptionTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0f172a',
    letterSpacing: -0.5,
  },
  subscriptionTagline: {
    fontSize: 15,
    color: '#64748b',
    fontWeight: '500',
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  closeButtonIcon: {
    fontSize: 20,
    color: '#111827',
    fontWeight: '900',
  },
  section: {
    gap: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 4,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 16,
  },
  loadingText: {
    fontSize: 14,
    color: '#6b7280',
  },
  planCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  planCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  planCardTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#111827',
  },
  planCardDescription: {
    fontSize: 14,
  },
  pendingTierText: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  trialBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#eef2ff',
  },
  trialBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4f46e5',
  },
  activeBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#d1fae5',
  },
  activeBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#065f46',
  },
  cancelWarning: {
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#f59e0b',
  },
  cancelWarningText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400e',
  },
  quotaInfoContainer: {
    gap: 8,
    marginTop: 8,
  },
  quotaInfoText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  quotaProgressBarFull: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: '#e5e7eb',
    overflow: 'hidden',
  },
  quotaProgressFillFull: {
    height: '100%',
    borderRadius: 999,
  },
  quotaWarningText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400e',
  },
  quotaExceededTextFull: {
    fontSize: 12,
    fontWeight: '600',
    color: '#991b1b',
  },
  statsCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  statLabel: {
    fontSize: 14,
    color: '#6b7280',
    lineHeight: 20,
  },
  statValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  tierCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    marginBottom: 12,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  tierCardSelected: {
    borderColor: '#f97316',
    borderWidth: 2.5,
    backgroundColor: '#fff7ed',
  },
  tierCardPopular: {
    borderColor: '#f97316',
    backgroundColor: '#ffffff',
    shadowColor: '#f97316',
    shadowOpacity: 0.12,
  },
  tierCardActive: {
    borderColor: '#f97316',
    backgroundColor: '#fff7ed',
  },
  popularRibbon: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#f97316',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderTopRightRadius: 14,
    borderBottomLeftRadius: 10,
  },
  popularRibbonText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },
  tierCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  tierCardTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
  },
  tierCardPrice: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ea580c',
    marginTop: 4,
  },
  tierCardQuota: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  currentBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#d1fae5',
  },
  currentBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#065f46',
  },
  actionButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  secondaryActionButton: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOpacity: 0.1,
  },
  secondaryActionButtonText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 15,
  },
  cancelButton: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#ef4444',
    marginTop: 8,
  },
  cancelButtonText: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 15,
  },
  toastContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    zIndex: 9999,
    elevation: 9999,
  },
  toastInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  toastIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  toastIconText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 16,
  },
  toastTextWrap: {
    flex: 1,
    gap: 1,
  },
  toastTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
  toastMessage: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 17,
  },
  dialogBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  dialogCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingVertical: 28,
    paddingHorizontal: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    elevation: 16,
  },
  dialogTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0F172A',
    letterSpacing: -0.3,
    marginBottom: 10,
  },
  dialogMessage: {
    fontSize: 15,
    fontWeight: '400',
    color: '#64748B',
    lineHeight: 22,
    marginBottom: 24,
  },
  dialogActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  dialogCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
  },
  dialogCancelText: {
    color: '#0F172A',
    fontWeight: '600',
    fontSize: 15,
  },
  dialogConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#0F172A',
    alignItems: 'center',
  },
  dialogConfirmDestructive: {
    backgroundColor: '#0F172A',
  },
  dialogConfirmText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
  },
  dialogConfirmTextDestructive: {
    color: '#FFFFFF',
  },
  dialogNeutralButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  dialogNeutralDestructive: {
    borderColor: '#EF4444',
    backgroundColor: '#FFFFFF',
  },
  dialogNeutralText: {
    color: '#0F172A',
    fontWeight: '600',
    fontSize: 15,
  },
  dialogNeutralTextDestructive: {
    color: '#EF4444',
  },
});
