// Styles configuration - protected on server
// Catalog: 160 styles from Funnyfy_Categories_Updated.xlsx (placeholders, disabled by default)
// Live styles: LEGACY_STYLES in this file (prompts, models, enabled flag)
//
// >>> Add new enabled styles to LEGACY_STYLES below. <<<
// Single source of truth — all API routes import from this file.

import { STYLE_CATALOG } from './style-catalog';

export interface StyleConfig {
  id: string;
  label: string;
  categoryId: string;
  description?: string;
  prompt: string;
  model: string;
  premium?: boolean;
  enabled?: boolean;
}

const DEFAULT_MODEL = 'black-forest-labs/flux-kontext-pro';
const NANO_BANANA = 'google/nano-banana';
const NANO_BANANA_2 = 'google/nano-banana-2';
const SEEDREAM_4 = 'bytedance/seedream-4';
const SEEDREAM_4_5 = 'bytedance/seedream-4.5';

function placeholderPrompt(label: string): string {
  return (
    `Transform this photo into a ${label} caricature. ` +
    `Preserve facial likeness with playful exaggeration. ` +
    `Style: ${label}. Full-bleed composition. No borders.`
  );
}

function catalogPlaceholders(): Record<string, StyleConfig> {
  return Object.fromEntries(
    STYLE_CATALOG.map((entry) => [
      entry.id,
      {
        id: entry.id,
        label: entry.label,
        categoryId: entry.categoryId,
        description: `${entry.label} — coming soon`,
        prompt: placeholderPrompt(entry.label),
        model: DEFAULT_MODEL,
        enabled: false,
        premium: false,
      },
    ]),
  );
}

/** Live styles — not in spreadsheet IDs; kept for backward compatibility with jobs/gallery */
const LEGACY_STYLES: Record<string, StyleConfig> = {
  '90s-cartoon': {
    id: '90s-cartoon',
    label: '90s',
    categoryId: 'cartoons',
    description: 'Classic 90s animated cartoon style',
    prompt: 'Make this a 90s cartoon',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  chibi: {
    id: 'chibi',
    label: 'Chibi',
    categoryId: 'cartoons',
    description: 'Cute, big-head chibi cartoon style',
    prompt: 'Make this a chibi cartoon, maintaining posture and facial features',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'classic-v1': {
    id: 'classic-v1',
    label: 'Classic V1',
    categoryId: 'cartoons',
    description: 'Classic cartoon style with timeless animated character appeal',
    prompt: 'make this a Classic Cartoon',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'classic-v2': {
    id: 'classic-v2',
    label: 'Classic V2',
    categoryId: 'cartoons',
    description: 'Classic cartoon style with bold lines and expressive character design',
    prompt: 'make this a Classic Cartoon',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  'saturday-v1': {
    id: 'saturday-v1',
    label: 'Saturday V1',
    categoryId: 'cartoons',
    description: 'Saturday morning cartoon style with bright colors and playful energy',
    prompt: 'make this a Saturday Morning Cartoon',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  'saturday-v2': {
    id: 'saturday-v2',
    label: 'Saturday V2',
    categoryId: 'cartoons',
    description: 'Saturday morning cartoon style with bold outlines and cheerful animation',
    prompt: 'make this a Saturday Morning Cartoon',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  comic: {
    id: 'comic',
    label: 'Comic',
    categoryId: 'cartoons',
    description: 'Comic cartoon style with bold ink lines and expressive character art',
    prompt: 'make this a comic Cartoon',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  cute: {
    id: 'cute',
    label: 'Cute',
    categoryId: 'cartoons',
    description: 'Cute cartoon style with soft shapes and adorable character charm',
    prompt: 'make this a cute Cartoon',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  dc: {
    id: 'dc',
    label: 'DC',
    categoryId: 'cartoons',
    description: 'DC style cartoon with bold superhero comic-book character design',
    prompt: 'make this a DC style Cartoon',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'cyberpunk-v1': {
    id: 'cyberpunk-v1',
    label: 'Cyberpunk V1',
    categoryId: 'cartoons',
    description: 'Cyberpunk cartoon style with neon-lit futuristic character design',
    prompt: 'make this a cyberpunk style cartoon, no extra text',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  'cyberpunk-v2': {
    id: 'cyberpunk-v2',
    label: 'Cyberpunk V2',
    categoryId: 'cartoons',
    description: 'Cyberpunk cartoon style with bold sci-fi edges and vivid neon color',
    prompt: 'make this a cyberpunk style cartoon, no extra text',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  disney: {
    id: 'disney',
    label: 'Disney',
    categoryId: 'cartoons',
    description: 'Disney-style cartoon with soft features and classic animated character charm',
    prompt: 'make this a disney style cartoon, no extra text',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  pixel: {
    id: 'pixel',
    label: 'Pixel',
    categoryId: 'cartoons',
    description: 'Pixel cartoon style with retro game-art charm',
    prompt: 'make this a pixel cartoon',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  '3d-render-v1': {
    id: '3d-render-v1',
    label: '3D Render V1',
    categoryId: 'cartoons',
    description: '3D rendered art cartoon with polished CGI character styling',
    prompt: 'make all subjects and object a 3D Rendered Art cartoon',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  '3d-render-v2': {
    id: '3d-render-v2',
    label: '3D Render V2',
    categoryId: 'cartoons',
    description: '3D rendered art cartoon with vivid stylized CGI illustration',
    prompt: 'make all subjects and object a 3D Rendered Art cartoon',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  'comic-v1': {
    id: 'comic-v1',
    label: 'Comic V1',
    categoryId: 'cartoons',
    description: 'Comic book style cartoon with classic printed-panel energy',
    prompt: 'make this a Comic Book Style cartoon',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'comic-v2': {
    id: 'comic-v2',
    label: 'Comic V2',
    categoryId: 'cartoons',
    description: 'Comic book style cartoon with sharper modern illustrated rendering',
    prompt: 'make this a Comic Book Style cartoon',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  neon: {
    id: 'neon',
    label: 'Neon',
    categoryId: 'art',
    description: 'Vibrant neon cartoon style',
    prompt: 'make a neon cartoon',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  anime: {
    id: 'anime',
    label: 'Anime',
    categoryId: 'anime-manga',
    description: 'Anime-style cartoon',
    prompt: 'Make this an anime cartoon, maintaining poster and facial features',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  custom1: {
    id: 'custom1',
    label: 'Custom 1',
    categoryId: 'trending',
    description: 'Digital cartoon illustration with vibrant colors and proportion exaggeration',
    prompt:
      "Using the uploaded photo as the facial reference, create a digital cartoon illustration of the same subject. Preserve the subject's recognizable facial likeness, while applying stylized, cartoon-like exaggeration. The subject is dressed in random shirt that fits snugly around a rounded torso, paired with random trousers that are slightly loose at the legs, and random shoes. His arms hang naturally by his sides, with relaxed but slightly clenched hands. The background is a bright blue sky with soft, fluffy white clouds, creating an open, cheerful atmosphere that contrasts with the subject's serious expression. Style: clean, polished contemporary digital cartoon illustration, with smooth linework, vibrant colors, and intentional proportion exaggeration (large head, simplified body). Maintain clarity, balanced proportions, and a friendly cartoon aesthetic. Full-bleed composition. No borders. No photorealism.",
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  '3dclay': {
    id: '3dclay',
    label: '3D Clay',
    categoryId: '3d-characters',
    description: '3D Clay cartoon style',
    prompt: 'make this a 3D Clay cartoon',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'oil-paint': {
    id: 'oil-paint',
    label: 'Oil Paint',
    categoryId: 'paintings',
    description: 'Oil-paint cartoon caricature style',
    prompt: 'make this a Oil-paint cartoon caricature',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  lowpoly: {
    id: 'lowpoly',
    label: 'Low Poly',
    categoryId: 'art',
    description: 'Low-poly cartoon with geometric facets and plain-color background',
    prompt: 'make this a low-poly cartoon, make background plain color if none.',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  mural: {
    id: 'mural',
    label: 'Mural',
    categoryId: 'art',
    description: 'Street mural graffiti portrait of the subject',
    prompt: 'make a street mural graffiti of the subject/s',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  'pop-art-v1': {
    id: 'pop-art-v1',
    label: 'Pop Art V1',
    categoryId: 'art',
    description: 'Pop art portrait rendered with bold flat colors',
    prompt: 'make this a pop art.',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'pop-art-v2': {
    id: 'pop-art-v2',
    label: 'Pop Art V2',
    categoryId: 'art',
    description: 'Pop art portrait with vibrant graphic styling',
    prompt: 'make this a pop art.',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'pop-art-v3': {
    id: 'pop-art-v3',
    label: 'Pop Art V3',
    categoryId: 'art',
    description: 'Pop art portrait with bold comic-inspired color blocks',
    prompt: 'make this a pop art.',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  graffiti: {
    id: 'graffiti',
    label: 'Graffiti',
    categoryId: 'art',
    description: 'Graffiti art portrait with bold street-art styling',
    prompt: 'make this a Graffiti Art.',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  banksy: {
    id: 'banksy',
    label: 'Banksy',
    categoryId: 'art',
    description: 'Banksy-style stencil street art portrait',
    prompt: 'make this a banksy style art',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  mosaic: {
    id: 'mosaic',
    label: 'Mosaic',
    categoryId: 'art',
    description: 'Mosaic installation art portrait with tiled color fragments',
    prompt: 'make this a Mosaic installations art',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'e-glow': {
    id: 'e-glow',
    label: 'E-Glow',
    categoryId: 'art',
    description: 'Electric glow art portrait with neon luminous highlights',
    prompt: 'make this a Electric Glow art',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'abstract-v1': {
    id: 'abstract-v1',
    label: 'Abstract V1',
    categoryId: 'art',
    description: 'Abstract art portrait with bold shapes and expressive color',
    prompt: 'Make this an abstract art',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  'abstract-v2': {
    id: 'abstract-v2',
    label: 'Abstract V2',
    categoryId: 'art',
    description: 'Abstract art portrait with layered forms and vivid composition',
    prompt: 'Make this an abstract art',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  geometric: {
    id: 'geometric',
    label: 'Geometric',
    categoryId: 'art',
    description: 'Geometric art portrait with angular shapes and bold color blocks',
    prompt: 'Make this a geometric art',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  surreal: {
    id: 'surreal',
    label: 'Surreal',
    categoryId: 'art',
    description: 'Surreal art portrait with dreamlike forms and imaginative composition',
    prompt: 'Make this a surreal art',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  'coloured-glass': {
    id: 'coloured-glass',
    label: 'Coloured Glass',
    categoryId: 'art',
    description: 'Colored glass art portrait with luminous stained-glass styling',
    prompt: 'Make this a Colored Glass Art',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'paste-up': {
    id: 'paste-up',
    label: 'Paste-up',
    categoryId: 'art',
    description: 'Paste-up street art portrait with layered paper collage styling',
    prompt: 'Make this a Paste-up Art',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'water-color': {
    id: 'water-color',
    label: 'Water Color',
    categoryId: 'paintings',
    description: 'Water color cartoon caricature style',
    prompt: 'make this a water color cartoon caricature',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  acrylic: {
    id: 'acrylic',
    label: 'Acrylic',
    categoryId: 'paintings',
    description: 'Acrylic painting portrait with bold brushstrokes and vibrant color',
    prompt: 'Make this an Acrylic Painting',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  gouache: {
    id: 'gouache',
    label: 'Gouache',
    categoryId: 'paintings',
    description: 'Gouache painting portrait with matte opaque washes and rich color',
    prompt: 'Make this a Gouache Painting',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  expressionist: {
    id: 'expressionist',
    label: 'Expressionist',
    categoryId: 'paintings',
    description: 'Expressionist painting portrait with bold brushwork and emotional color',
    prompt: 'make this an Expressionist painting',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  impressionist: {
    id: 'impressionist',
    label: 'Impressionist',
    categoryId: 'paintings',
    description: 'Impressionist painting portrait with soft brushstrokes and luminous color',
    prompt: 'make this an Impressionist painting',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  baroque: {
    id: 'baroque',
    label: 'Baroque',
    categoryId: 'paintings',
    description: 'Baroque portrait painting with dramatic lighting and rich classical detail',
    prompt: 'make this a Baroque Portrait painting',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'van-gogh': {
    id: 'van-gogh',
    label: 'Van Gogh',
    categoryId: 'paintings',
    description: 'Van Gogh style painting with expressive brushstrokes and vivid swirling color',
    prompt:
      'An expressive Post-Impressionist oil painting featuring thick impasto brushstrokes, swirling directional paint strokes, vibrant complementary colors, textured canvas, energetic movement, dramatic lighting, bold painterly texture. Preserve the uploaded person\'s exact facial identity, age, hairstyle, facial structure, expression, and clothing. Transform only the artistic rendering, not the person\'s identity.',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  'expressive-impasto': {
    id: 'expressive-impasto',
    label: 'Expressive Impasto',
    categoryId: 'paintings',
    description: 'Expressive impasto oil painting with thick brushstrokes, vivid color, and dramatic post-impressionist texture',
    prompt:
      'An expressive Post-Impressionist oil painting featuring thick impasto brushstrokes, swirling directional paint strokes, vibrant complementary colors, textured canvas, energetic movement, dramatic lighting, bold painterly texture. Preserve the uploaded person\'s exact facial identity, age, hairstyle, facial structure, expression, and clothing. Transform only the artistic rendering, not the person\'s identity.',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  monet: {
    id: 'monet',
    label: 'Monet',
    categoryId: 'paintings',
    description: 'Monet style painting with soft impressionist light and delicate color',
    prompt: 'using this pic make this a monet style Painting',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  renoir: {
    id: 'renoir',
    label: 'Renoir',
    categoryId: 'paintings',
    description: 'Renoir inspired painting with warm impressionist tones and soft brushwork',
    prompt: 'using this pic make this a Renoir Inspired Painting',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  cezanne: {
    id: 'cezanne',
    label: 'Cézanne',
    categoryId: 'paintings',
    description: 'Cézanne inspired painting with structured forms and post-impressionist color',
    prompt: 'using this pic make this a Cézanne Inspired Painting',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  gauguin: {
    id: 'gauguin',
    label: 'Gauguin',
    categoryId: 'paintings',
    description: 'Gauguin inspired painting with bold color and post-impressionist tropical mood',
    prompt: 'using this pic make this a Gauguin Inspired Painting',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  matisse: {
    id: 'matisse',
    label: 'Matisse',
    categoryId: 'paintings',
    description: 'Matisse inspired painting with bold flat color and expressive fauvist forms',
    prompt: 'using this pic make this a Matisse Inspired Painting',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  seurat: {
    id: 'seurat',
    label: 'Seurat',
    categoryId: 'paintings',
    description: 'Seurat inspired painting with pointillist dots and luminous neo-impressionist color',
    prompt: 'using this pic make this a Seurat Inspired Painting',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  'ink-wash': {
    id: 'ink-wash',
    label: 'Ink-Wash',
    categoryId: 'paintings',
    description: 'Ink wash painting with fluid brushstrokes and delicate tonal washes',
    prompt: 'using this pic make this a Ink Wash Painting',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  impasto: {
    id: 'impasto',
    label: 'Impasto',
    categoryId: 'paintings',
    description: 'Impasto painting with thick textured brushstrokes and rich layered paint',
    prompt: 'using this pic make all subjects as an Impasto Painting',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  'hokusai-v1': {
    id: 'hokusai-v1',
    label: 'Hokusai V1',
    categoryId: 'paintings',
    description: 'Hokusai inspired painting with bold ukiyo-e lines and dramatic composition',
    prompt: 'using this pic make all subjects as a Hokusai Inspired Painting',
    model: SEEDREAM_4_5,
    enabled: true,
    premium: false,
  },
  'hokusai-v2': {
    id: 'hokusai-v2',
    label: 'Hokusai V2',
    categoryId: 'paintings',
    description: 'Hokusai inspired painting with vivid woodblock color and expressive brushwork',
    prompt: 'using this pic make all subjects as a Hokusai Inspired Painting',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  hiroshige: {
    id: 'hiroshige',
    label: 'Hiroshige',
    categoryId: 'paintings',
    description: 'Hiroshige inspired painting with elegant ukiyo-e landscapes and refined color',
    prompt: 'using this pic make all subjects as a Hiroshige Inspired Painting, no extra text',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  sesshu: {
    id: 'sesshu',
    label: 'Sesshū',
    categoryId: 'paintings',
    description: 'Sesshū inspired painting with ink-wash landscapes and meditative composition',
    prompt: 'using this pic make all subjects as a Sesshū Inspired Painting in color, no extra text',
    model: NANO_BANANA_2,
    enabled: true,
    premium: false,
  },
  'pixar-like': {
    id: 'pixar-like',
    label: 'Pixar-like',
    categoryId: '3d-characters',
    description: 'Pixar-like cartoon style including background',
    prompt: 'make this a pixar-like cartoon including the background',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  'funko-pop': {
    id: 'funko-pop',
    label: 'Funko Pop',
    categoryId: '3d-characters',
    description: 'Funko Pop style',
    prompt: 'make this a funko pop',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  custom2: {
    id: 'custom2',
    label: 'Custom 2',
    categoryId: 'trending',
    description: 'Stylized 3D cartoon caricature with soft, friendly animated style - supports multiple faces',
    prompt:
      'Using the uploaded photo as the reference, detect all clearly visible human faces in the image.Create a stylized 3D cartoon caricature of EACH person, preserving their individual facial likeness, skin tone, hairstyle, and expression.Do NOT merge faces and do NOT ignore secondary subjects. If multiple people are present:Apply the same 3D animated style consistently to all subjects, Maintain relative positions and scale between them,Keep each face distinct and recognizable,Reinterpret each person in a soft, friendly, animated 3D style with slightly exaggerated features, including: Large expressive eyes,Smooth rounded facial structure,Simplified nose and mouth,Warm, cheerful expressions,Skin should be smooth and matte, with soft lighting and no visible pores.Hair should be stylized and sculpted, with soft volume and clean shapes.Clothing should remain recognizable but simplified. Background may be simplified or softly blurred, but the relationship and interaction between subjects must be preserved.Render quality: polished 3D animated film style, clean geometry, soft shadows, warm color palette.Full-bleed composition. No borders. No photorealism.',
    model: DEFAULT_MODEL,
    enabled: true,
    premium: false,
  },
  neandc: {
    id: 'neandc',
    label: 'Neanderthal',
    categoryId: 'fantasy-mythical',
    description: 'Funny neanderthal cartoon maintaining facial features in a random Neanderthalic setting',
    prompt: 'make this a funny neanderthal cartoon maintaining facial features, in a random Neanderthalic setting',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  neand3d: {
    id: 'neand3d',
    label: 'Neanderthal 3D',
    categoryId: 'fantasy-mythical',
    description: 'Funny neanderthal 3D caricature maintaining facial features, detects and includes all humans',
    prompt:
      'make this a funny neanderthal 3d caricature maintaining facial features, in a random Neanderthalic setting. detect and include all humans in the photo, caricaturize all humans once detected',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  handd: {
    id: 'handd',
    label: 'Hand-Drawn',
    categoryId: 'caricatures',
    description: 'Traditional hand-drawn editorial caricature with colored-pencil and ink illustration style',
    prompt:
      "Using the uploaded photo as the visual reference, create a hand-drawn editorial caricature of the subject. The caricature should feature a very large, exaggerated head and a small, simplified body, preserving the subject's core facial likeness while emphasizing distinctive features. Strongly exaggerate: Head size and facial proportions, Nose, cheeks, jaw, and brow, Eye spacing and expression. Style: Traditional colored-pencil and ink illustration, Visible pencil strokes, Cross-hatching and line shading, Slightly uneven, hand-drawn outlines, Subtle paper texture. Shading should be: Built with layered pencil tones, Warm, earthy colors, No smooth digital gradients. Facial expression should be expressive and characterful, leaning slightly humorous or serious depending on the reference photo. Clothing should be simplified and secondary, drawn with minimal detail to keep focus on the face. Background: Plain, light, off-white or beige, Minimal texture only, No scenery, no environment. Overall look: Classic newspaper / magazine caricature, Hand-drawn, imperfect, human, Exaggerated but recognizable. Full-bleed illustration. No borders. Avoid 3D, avoid painterly styles, avoid realism.",
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  editorial: {
    id: 'editorial',
    label: 'Editorial',
    categoryId: 'caricatures',
    description:
      'Sophisticated magazine editorial caricature with ink linework and watercolor washes',
    prompt:
      'Create a sophisticated editorial caricature of the provided subject while faithfully preserving their identity, facial structure, age, ethnicity, hairstyle, expression, clothing, and pose. Exaggerate the defining facial characteristics in a tasteful editorial manner—slightly enlarge the head, emphasize the forehead, eyebrows, eyes, nose, ears, cheek lines, smile lines, and wrinkles to communicate wisdom and character without becoming grotesque. Maintain realistic facial proportions despite the stylization. Render in a premium newspaper/magazine editorial illustration style using expressive black ink linework, fine cross-hatching, loose pen strokes, and layered watercolor washes. Use warm, earthy tones with subtle texture from watercolor paper. Employ confident contour lines, varied line weights, and painterly shading to create depth while retaining a handcrafted appearance. Preserve the library setting with bookshelves and the armchair, but simplify the background into soft watercolor shapes and sketch-like details so it supports rather than competes with the subject. Use soft natural window lighting, gentle shadows, and a muted, elegant color palette. The overall mood should be thoughtful, distinguished, intellectual, and timeless—resembling a high-end editorial portrait published in The New Yorker, The Economist, Financial Times, or a literary magazine. No typography, captions, speech bubbles, logos, signatures, watermarks, borders, decorative frames, or graphic elements. Background should remain clean and uncluttered, with the subject as the clear focal point.',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  exaggerated: {
    id: 'exaggerated',
    label: 'Exaggerated',
    categoryId: 'caricatures',
    description: 'Exaggerated 3D cartoon caricature with playful proportions',
    prompt: 'Make this an Exaggerated 3d cartoon caricature',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  coloured_pencil: {
    id: 'coloured_pencil',
    label: 'Coloured Pencil',
    categoryId: 'caricatures',
    description: 'Colored pencil caricature rendered with premium stylized shading',
    prompt: 'Make this an Exaggerated 3d cartoon caricature',
    model: SEEDREAM_4,
    enabled: false, // re-enable after apps/mobile/assets/comparisons/after/caricature/colouredp.jpg is added
    premium: false,
  },
  watercolor: {
    id: 'watercolor',
    label: 'Watercolor',
    categoryId: 'caricatures',
    description: 'Watercolor caricature with soft painterly washes and stylized shading',
    prompt: 'Make this a Watercolor caricature',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  carc1: {
    id: 'carc1',
    label: 'Carc1',
    categoryId: 'caricatures',
    description:
      'Full-body stylized 3D caricature with oversized head, slim proportions, and premium character shading',
    prompt:
      'Using the uploaded photo as the sole identity reference, create a full-body stylized 3D caricature that faithfully preserves the person\'s recognizable facial features, body type, skin tone, ethnicity, hairstyle, facial hair, clothing, footwear, and accessories. The character should unmistakably resemble the person in the reference photo. Maintain a clean studio composition with the character standing upright in a relaxed pose, facing forward, with the entire body visible from head to toe. Apply a cohesive stylized character design with: An oversized head (approximately 1.8–2.2× realistic size), A very long, slim neck, A smaller, simplified torso, Long, thin arms and legs, Large expressive hands, Slightly oversized shoes, Gentle exaggeration of the person\'s natural facial features (nose, ears, jawline, cheeks, eyes, lips, eyebrows) while preserving identity, Expressive but believable proportions. Preserve the person\'s actual: race and skin tone, facial structure, hairstyle, facial hair, age appearance, body build (slim, average, muscular, heavy-set, etc.), clothing style, colors, textures and logos (unless copyright-safe replacements are required), accessories. Render using premium stylized 3D character artwork with: physically based materials, soft cinematic lighting, subtle skin texture, realistic fabric folds, clean matte surfaces, high-quality sculpted details, smooth stylized anatomy, slightly enlarged eyes with expressive brows. The expression should be natural and personality-driven rather than exaggerated into comedy. Keep the background completely transparent with no floor, shadows, props, or scenery. The final image should resemble a collectible animated film character or high-end stylized game character while remaining an unmistakable caricature of the person in the uploaded photograph.',
    model: SEEDREAM_4,
    enabled: true,
    premium: false,
  },
  superhero: {
    id: 'superhero',
    label: 'Superhero',
    categoryId: 'video-games',
    description: 'Superhero caricature in action, avoiding trademarked themes, maintaining facial and body features',
    prompt:
      'make a superhero caricature, in superhero costumes, avoid trademarked themes, set super hero actions like saving victims, stopping trains, stopping bad guys, etc. in random settings. maintain subjects facial and body features',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  villian: {
    id: 'villian',
    label: 'Super Villain',
    categoryId: 'video-games',
    description: 'Super villain caricature in action, avoiding trademarked themes, maintaining facial and body features',
    prompt:
      'make a super villain caricature, in superhero costumes, avoid trademarked themes, set super villan actions like chasing victims, destroying stuff being bad guys, etc, in random settings. maintain subjects facial and body features',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
  cyborg: {
    id: 'cyborg',
    label: 'Cyborg',
    categoryId: 'video-games',
    description: 'Cyborg cartoon caricature maintaining facial and body features, set in futuristic city settings',
    prompt:
      'make a cyborg cartoon caricature, maintaining subjects facial and body features, set in futuristic random city in random settings',
    model: NANO_BANANA,
    enabled: true,
    premium: false,
  },
};

export const STYLES_CONFIG: Record<string, StyleConfig> = {
  ...catalogPlaceholders(),
  ...LEGACY_STYLES,
};

export function getStyleById(styleId: string): StyleConfig | null {
  const style = STYLES_CONFIG[styleId];
  if (!style || !style.enabled) {
    return null;
  }
  return style;
}

export function getEnabledStyles(): StyleConfig[] {
  return Object.values(STYLES_CONFIG).filter((style) => style.enabled !== false);
}

export function getFreeStyles(): StyleConfig[] {
  return getEnabledStyles().filter((style) => !style.premium);
}
