// Auto-generated from Funnyfy_Categories_Updated.xlsx

export interface StyleCatalogEntry {
  id: string;
  label: string;
  categoryId: string;
}

export interface StyleCategory {
  id: string;
  label: string;
}

export const STYLE_CATEGORIES: StyleCategory[] = [
  { id: 'moods-moments', label: "Moods & Moments" },
  { id: 'caricatures', label: "Caricatures" },
  { id: 'tinyme', label: "TinyMe" },
  { id: 'cartoons', label: "Cartoons" },
  { id: '3d-characters', label: "3D Characters" },
  { id: 'anime-manga', label: "Anime & Manga" },
  { id: 'stickers-emojis', label: "Stickers & Emojis" },
  { id: 'paintings', label: "Paintings" },
  { id: 'drawings-sketches', label: "Drawings & Sketches" },
  { id: 'historical', label: "Historical" },
  { id: 'art', label: "Art" },
  { id: 'professions', label: "Professions" },
  { id: 'seasonal-events', label: "Seasonal & Events" },
];

export const STYLE_CATALOG: StyleCatalogEntry[] = [
  { id: "editorial-caricature", label: "Editorial Caricature", categoryId: "caricatures" },
  { id: "exaggerated-caricature", label: "Exaggerated Caricature", categoryId: "caricatures" },
  { id: "big-head-small-body", label: "Big Head Small Body", categoryId: "caricatures" },
  { id: "political-cartoon-style", label: "Political Cartoon Style", categoryId: "caricatures" },
  { id: "colored-pencil-caricature", label: "Colored Pencil Caricature", categoryId: "caricatures" },
  { id: "watercolor-caricature", label: "Watercolor Caricature", categoryId: "caricatures" },
  { id: "celebrity-caricature", label: "Celebrity Caricature", categoryId: "caricatures" },
  { id: "street-artist-caricature", label: "Street Artist Caricature", categoryId: "caricatures" },
  { id: "funny-business-portrait", label: "Funny Business Portrait", categoryId: "caricatures" },
  { id: "theme-park-caricature", label: "Theme Park Caricature", categoryId: "caricatures" },
  { id: "monday-mood", label: "Monday", categoryId: "moods-moments" },
  { id: "friday-feeling", label: "Friday", categoryId: "moods-moments" },
  { id: "payday", label: "Payday", categoryId: "moods-moments" },
  { id: "end-of-month", label: "End of Month", categoryId: "moods-moments" },
  { id: "before-coffee", label: "Before Coffee", categoryId: "moods-moments" },
  { id: "after-coffee", label: "After Coffee", categoryId: "moods-moments" },
  { id: "deadline-mode", label: "Deadline Mode", categoryId: "moods-moments" },
  { id: "vacation-mood", label: "Vacation Mood", categoryId: "moods-moments" },
  { id: "gym-motivation", label: "Gym Motivation", categoryId: "moods-moments" },
  { id: "forgot-my-password", label: "Forgot My Password", categoryId: "moods-moments" },
  { id: "tiny-office-worker", label: "Tiny Office Worker", categoryId: "tinyme" },
  { id: "tiny-superhero", label: "Tiny Superhero", categoryId: "tinyme" },
  { id: "tiny-explorer", label: "Tiny Explorer", categoryId: "tinyme" },
  { id: "tiny-chef", label: "Tiny Chef", categoryId: "tinyme" },
  { id: "tiny-astronaut", label: "Tiny Astronaut", categoryId: "tinyme" },
  { id: "tiny-rockstar", label: "Tiny Rockstar", categoryId: "tinyme" },
  { id: "tiny-builder", label: "Tiny Builder", categoryId: "tinyme" },
  { id: "tiny-farmer", label: "Tiny Farmer", categoryId: "tinyme" },
  { id: "tiny-sports-star", label: "Tiny Sports Star", categoryId: "tinyme" },
  { id: "tiny-fantasy-hero", label: "Tiny Fantasy Hero", categoryId: "tinyme" },
  { id: "classic-cartoon", label: "Classic Cartoon", categoryId: "cartoons" },
  { id: "saturday-morning-cartoon", label: "Saturday Morning Cartoon", categoryId: "cartoons" },
  { id: "comic-cartoon", label: "Comic Cartoon", categoryId: "cartoons" },
  { id: "cute-cartoon", label: "Cute Cartoon", categoryId: "cartoons" },
  { id: "funny-cartoon", label: "Funny Cartoon", categoryId: "cartoons" },
  { id: "tv-animation", label: "TV Animation", categoryId: "cartoons" },
  { id: "toon-portrait", label: "Toon Portrait", categoryId: "cartoons" },
  { id: "chibi-cartoon", label: "Chibi Cartoon", categoryId: "cartoons" },
  { id: "retro-cartoon", label: "Retro Cartoon", categoryId: "cartoons" },
  { id: "newspaper-cartoon", label: "Newspaper Cartoon", categoryId: "cartoons" },
  { id: "pixar-inspired", label: "Pixar-Inspired", categoryId: "3d-characters" },
  { id: "toy-character", label: "Toy Character", categoryId: "3d-characters" },
  { id: "clay-character", label: "Clay Character", categoryId: "3d-characters" },
  { id: "plastic-figure", label: "Plastic Figure", categoryId: "3d-characters" },
  { id: "vinyl-toy", label: "Vinyl Toy", categoryId: "3d-characters" },
  { id: "3d-cartoon", label: "3D Cartoon", categoryId: "3d-characters" },
  { id: "cute-mascot", label: "Cute Mascot", categoryId: "3d-characters" },
  { id: "cgi-character", label: "CGI Character", categoryId: "3d-characters" },
  { id: "theme-park-character", label: "Theme Park Character", categoryId: "3d-characters" },
  { id: "mini-figurine", label: "Mini Figurine", categoryId: "3d-characters" },
  { id: "shonen-anime", label: "Shonen Anime", categoryId: "anime-manga" },
  { id: "shojo-anime", label: "Shojo Anime", categoryId: "anime-manga" },
  { id: "manga-panel", label: "Manga Panel", categoryId: "anime-manga" },
  { id: "chibi-anime", label: "Chibi Anime", categoryId: "anime-manga" },
  { id: "fantasy-anime", label: "Fantasy Anime", categoryId: "anime-manga" },
  { id: "action-anime", label: "Action Anime", categoryId: "anime-manga" },
  { id: "school-anime", label: "School Anime", categoryId: "anime-manga" },
  { id: "mecha-anime", label: "Mecha Anime", categoryId: "anime-manga" },
  { id: "samurai-anime", label: "Samurai Anime", categoryId: "anime-manga" },
  { id: "modern-anime", label: "Modern Anime", categoryId: "anime-manga" },
  { id: "whatsapp-sticker", label: "WhatsApp Sticker", categoryId: "stickers-emojis" },
  { id: "telegram-sticker", label: "Telegram Sticker", categoryId: "stickers-emojis" },
  { id: "cute-emoji", label: "Cute Emoji", categoryId: "stickers-emojis" },
  { id: "meme-sticker", label: "Meme Sticker", categoryId: "stickers-emojis" },
  { id: "reaction-sticker", label: "Reaction Sticker", categoryId: "stickers-emojis" },
  { id: "kawaii-sticker", label: "Kawaii Sticker", categoryId: "stickers-emojis" },
  { id: "chibi-sticker", label: "Chibi Sticker", categoryId: "stickers-emojis" },
  { id: "cartoon-sticker", label: "Cartoon Sticker", categoryId: "stickers-emojis" },
  { id: "badge-sticker", label: "Badge Sticker", categoryId: "stickers-emojis" },
  { id: "die-cut-sticker", label: "Die-Cut Sticker", categoryId: "stickers-emojis" },
  { id: "oil-painting", label: "Oil Painting", categoryId: "paintings" },
  { id: "watercolor", label: "Watercolor", categoryId: "paintings" },
  { id: "acrylic-painting", label: "Acrylic Painting", categoryId: "paintings" },
  { id: "gouache", label: "Gouache", categoryId: "paintings" },
  { id: "impressionist", label: "Impressionist", categoryId: "paintings" },
  { id: "expressionist", label: "Expressionist", categoryId: "paintings" },
  { id: "renaissance-portrait", label: "Renaissance Portrait", categoryId: "paintings" },
  { id: "baroque-portrait", label: "Baroque Portrait", categoryId: "paintings" },
  { id: "modern-art", label: "Modern Art", categoryId: "paintings" },
  { id: "gallery-canvas", label: "Gallery Canvas", categoryId: "paintings" },
  { id: "pencil-sketch", label: "Pencil Sketch", categoryId: "drawings-sketches" },
  { id: "charcoal-drawing", label: "Charcoal Drawing", categoryId: "drawings-sketches" },
  { id: "ink-drawing", label: "Ink Drawing", categoryId: "drawings-sketches" },
  { id: "pen-illustration", label: "Pen Illustration", categoryId: "drawings-sketches" },
  { id: "cross-hatch", label: "Cross Hatch", categoryId: "drawings-sketches" },
  { id: "line-art", label: "Line Art", categoryId: "drawings-sketches" },
  { id: "fashion-sketch", label: "Fashion Sketch", categoryId: "drawings-sketches" },
  { id: "architectural-sketch", label: "Architectural Sketch", categoryId: "drawings-sketches" },
  { id: "storybook-drawing", label: "Storybook Drawing", categoryId: "drawings-sketches" },
  { id: "marker-drawing", label: "Marker Drawing", categoryId: "drawings-sketches" },
  { id: "ancient-egyptian", label: "Ancient Egyptian", categoryId: "historical" },
  { id: "roman-sculpture", label: "Roman Sculpture", categoryId: "historical" },
  { id: "renaissance-noble", label: "Renaissance Noble", categoryId: "historical" },
  { id: "victorian-portrait", label: "Victorian Portrait", categoryId: "historical" },
  { id: "medieval-knight", label: "Medieval Knight", categoryId: "historical" },
  { id: "royal-king", label: "Royal King", categoryId: "historical" },
  { id: "queen-portrait", label: "Queen Portrait", categoryId: "historical" },
  { id: "ancient-warrior", label: "Ancient Warrior", categoryId: "historical" },
  { id: "samurai", label: "Samurai", categoryId: "historical" },
  { id: "pharaoh", label: "Pharaoh", categoryId: "historical" },
  { id: "pop-art", label: "Pop Art", categoryId: "art" },
  { id: "graffiti-art", label: "Graffiti Art", categoryId: "art" },
  { id: "street-art", label: "Street Art", categoryId: "art" },
  { id: "colored-glass-art", label: "Colored Glass Art", categoryId: "art" },
  { id: "mosaic-art", label: "Mosaic Art", categoryId: "art" },
  { id: "paper-cut-art", label: "Paper Cut Art", categoryId: "art" },
  { id: "low-poly-art", label: "Low Poly Art", categoryId: "art" },
  { id: "abstract-art", label: "Abstract Art", categoryId: "art" },
  { id: "geometric-art", label: "Geometric Art", categoryId: "art" },
  { id: "surreal-art", label: "Surreal Art", categoryId: "art" },
  { id: "doctor", label: "Doctor", categoryId: "professions" },
  { id: "pilot", label: "Pilot", categoryId: "professions" },
  { id: "firefighter", label: "Firefighter", categoryId: "professions" },
  { id: "chef", label: "Chef", categoryId: "professions" },
  { id: "teacher", label: "Teacher", categoryId: "professions" },
  { id: "engineer", label: "Engineer", categoryId: "professions" },
  { id: "astronaut", label: "Astronaut", categoryId: "professions" },
  { id: "detective", label: "Detective", categoryId: "professions" },
  { id: "scientist", label: "Scientist", categoryId: "professions" },
  { id: "musician", label: "Musician", categoryId: "professions" },
  { id: "christmas", label: "Christmas", categoryId: "seasonal-events" },
  { id: "halloween", label: "Halloween", categoryId: "seasonal-events" },
  { id: "valentine-s", label: "Valentine's", categoryId: "seasonal-events" },
  { id: "easter", label: "Easter", categoryId: "seasonal-events" },
  { id: "birthday", label: "Birthday", categoryId: "seasonal-events" },
  { id: "graduation", label: "Graduation", categoryId: "seasonal-events" },
  { id: "wedding", label: "Wedding", categoryId: "seasonal-events" },
  { id: "new-year", label: "New Year", categoryId: "seasonal-events" },
  { id: "father-s-day", label: "Father's Day", categoryId: "seasonal-events" },
  { id: "mother-s-day", label: "Mother's Day", categoryId: "seasonal-events" },
  { id: "action-figure-box", label: "Action Figure Box", categoryId: "cartoons" },
  { id: "funny-figure-box", label: "Funny Figure Box", categoryId: "cartoons" },
  { id: "collectible-toy", label: "Collectible Toy", categoryId: "cartoons" },
  { id: "ai-passport-photo", label: "AI Passport Photo", categoryId: "art" },
  { id: "vintage-poster", label: "Vintage Poster", categoryId: "art" },
  { id: "movie-poster", label: "Movie Poster", categoryId: "art" },
  { id: "magazine-cover", label: "Magazine Cover", categoryId: "art" },
  { id: "trading-card", label: "Trading Card", categoryId: "art" },
  { id: "sports-card", label: "Sports Card", categoryId: "art" },
  { id: "wanted-poster", label: "Wanted Poster", categoryId: "art" },
];

export const CATALOG_STYLE_COUNT = 160;
